### ISSUE TITLE
TypeError: The plugin "add-module-exports" didn't export a Plugin instance

### ISSUE THREAD

**Issue by joshmanders** [59naga/babel-plugin-add-module-exports#17]
I have no idea how to even go about fixing this.

**devDependencies**

```
"babel-core": "6.2.1",
"babel-plugin-add-module-exports": "0.1.1",
"babel-preset-es2015": "6.1.18",
"babel-preset-stage-0": "6.1.18"

**Comment by kentcdodds** [comment]
@killswitch, I was unable to reproduce your issue. Please see [this repo](https://github.com/kentcdodds/babel-plugin-add-module-exports-issue-17).

Steps:

1. Clone the repo
2. `npm install`
3. `npm run test`
4. See the output: `assertions passed`
5. Remove the plugin from the `.babelrc`
6. `npm run test`
7. See the runtime error
8. Dig deeper to figure out why you're experiencing this issue
9. Get it solved.
10. Celebrate! 🎊 🎉

**Comment by killswitch** [comment]
That's because you're not exporting a default function or variable.

https://github.com/kentcdodds/babel-plugin-add-module-exports-issue-17/blob/master/math.js#L1

Try this:

```js
export default function  add (a, b) {
  return a + b
}

export function multiply (a, b) {
   return a * b
}
```

Look at the generated code without the plugin, you should see

```js

exports['multiply'] = function multiply (a, b) {
   return a * b
}
exports['default'] = function add (a, b) {
  return a + b
}
```

To get `add` you have to do `var add = require('math').default` when I should be able to do `var add = require('math')`

Also note I do not use `.babelrc` I am running `babel src --out-dir dist --presets es2015,stage-0 --plugins add-module-exports` from the terminal

**Comment by kentcdodds** [comment]
hmm... I'll look at that. If you're running it via the command line, make sure you're using the bin you think you are. You may have the latest version of babel in your `devDependencies`, but if you're simply running `babel` from the command line it's going to use your global install of babel. Make sure you reference it properly: `node_modules/.bin/babel` or use a script in your `package.json`

**Comment by kentcdodds** [comment]
Ah, yeah, found the bug you're talking about... Pushing...

**Comment by killswitch** [comment]
Ideally the plugin should make it so named exports are available and default export is set on `module.exports` so the following will work:

```js
export const GREET_PREFIX = 'hello'

export class Greeter {
  constructor (user) {
    this.user = user
  }

  greet (message) {
    console.log(`${GREET_PREFIX} ${this.user}, ${message}`)
}

export default function (user, message) {
  return (new Greeter(user)).greet(message)
}
```

Then used here:

```js
var greet = require('greet')
var Greet = require('greet').Greeter
greet('Josh', 'How are you?')

var kent = new Greeter('Kent')
kent.greet('JavaScript is fun, amirite?')
```

**Comment by kentcdodds** [comment]
The repo now reproduces the bug: https://github.com/kentcdodds/babel-plugin-add-module-exports-issue-17

Basically when you have multiple exports (as in [bad.js](https://github.com/kentcdodds/babel-plugin-add-module-exports-issue-17/blob/master/bad.js)), it's not adding the in the [output](https://github.com/kentcdodds/babel-plugin-add-module-exports-issue-17/blob/master/bad.out.js): `module.exports = exports['default'];` (as in [good.js](https://github.com/kentcdodds/babel-plugin-add-module-exports-issue-17/blob/master/good.js) and it's [output](https://github.com/kentcdodds/babel-plugin-add-module-exports-issue-17/blob/master/good.out.js))

**Comment by kentcdodds** [comment]
But @killswitch, you said that this used to work and a babel release broke it?

**Comment by killswitch** [comment]
I assumed it worked, but after I forked it and attempted to fix it myself with lackluster documentation on Babel's part regarding writing plugins, I found out that it only worked if all it exported was default. You cannot export named and default and get it. Which makes my example above still not possible.

**Comment by killswitch** [comment]
Okay, so what I had differently than you was you have `babel-cli` in `devDependencies` and I didn't. So I added that and the plugin interface issue is gone.

Inconsistent api's on babel 6 packages. Yay. 😬

**Comment by lijunle** [comment]
Hi, @kentcdodds Could you please convert your repro as a test case in [spec.js](https://github.com/59naga/babel-plugin-add-module-exports/blob/master/test/spec.js). That could be great to avoid regression.

**Comment by kentcdodds** [comment]
Hi @lijunle! I'll see if I get a chance. Honestly I don't really have a use case for this. I was just trying to help @killswitch out a bit :-)

**Comment by lijunle** [comment]
Hmm.... I looked into your repo code, that behavior is **expected**.

This repo is following what Babel@5 does:

- If only `default` is exposed, move `default` as `module.exports`
- If more than `default` is exposed, access them `module.exports[name]`.

You can try with the current REPL, which is currently still with version 5. Here is the [code](https://babeljs.io/repl/#?experimental=false&evaluate=true&loose=false&spec=false&code=export%20default%20function%20%20add%20%28a%2C%20b%29%20{%0A%20%20return%20a%20%2B%20b%0A}%0A%0Aexport%20function%20multiply%20%28a%2C%20b%29%20{%0A%20%20%20return%20a%20*%20b%0A}).

**Comment by killswitch** [comment]
Is there any reason why you can't have named exports and a default export?

**Comment by lijunle** [comment]
In that case, it might need to `mix(default, { other, named, exports })`. However, such mix-in will mess up things, check [this comment](https://github.com/59naga/babel-plugin-add-module-exports/issues/4#issuecomment-156676341) as an example.

**Comment by killswitch** [comment]
Eh, that behavior happens whether you use Module Import/Export or just use `exports` and `module.exports` outright. I don't think imposing personal views on end users is a good idea. It's better to let them know of the caveats over saying "no, we don't want you to make an error, so we're going to hold your hand."

**Comment by lijunle** [comment]
> It's better to let them know of the caveats...

I think that is the reason why Babel@6 just kill the CommonJS backward compatibility. If you read the Babel's discussion, sebmck [mentioned](https://phabricator.babeljs.io/T2212#57711) another wrong use for the caveats.

**Comment by killswitch** [comment]
The discussion on there is valid and an exact reason I want this behavior. 

> I really can't tell anyone building a node app to also use Babel to transpile their app to avoid some non idiomatic import with my module. they just won't use my module instead

Boom, right there. Telling my users to do `var thing = require('thing').default` is out not ideal and telling them to use Babel to get around that is absolutely out of the question.

```js
module.exports = require('./transpiled/index').default;
```

That is definitely out of question too, the whole point of allowing named and default is so I can expose an API to my users. Having a single proxy file makes that ability invalid.

I'd personally stop using Babel over imposing any of that on my users. But I'd prefer to write ES2015.

**Comment by killswitch** [comment]
While I see the benefits of not using it, that's more of imposing Babel's coding standards on it's users. Babel is a tool to transpile code, not tell me HOW to write my code.

```js
export default { x: 1 };
export const x = 2;
```

I can accomplish that in ES5 also doing

```js
exports = module.exports = { x: 1 }
exports.x = 2
```

And it works the exact same, but Node does not get in the way. I believe that it's up to the developer to understand that they're overwriting a previous value, and their transpiling tool should not magically fix it.

**Comment by killswitch** [comment]
Maybe make it opt-in? I know plugins can have options, so why not offer both, and make it opt-out by default?

**Comment by lijunle** [comment]
IMO, no. However, it is up to @59naga 's decision.

> I believe that it's up to the developer to understand that they're overwriting a previous value

I don't think any developer will understand they are overwriting exports. Make the code predictable and manageable.

> And it works the exact same

No, the ES5 will **not** work as same as the ES6 one. Not only nodejs, but also any JavaScript engine.

> Node does not get in the way

I agree that the problem is on the nodejs side (V8 engine). Concretely, the problem is, **how to make ES6 module be compatible to work in ES5 code**.

I have no answer, but I know that directly overwriting the exports is not a right solution. Node team members has some [discussion](https://github.com/nodejs/NG/issues/5) about this. However, they are still on the strategy stage. 

If there is a way to make such compatibility happens, we could just implement it in this plugin. But, at the current stage, use the safe way.

BTW, if nodejs finally says, such compatibility does not exist, what will happen, what will you do?

**Comment by killswitch** [comment]
> BTW, if nodejs finally says, such compatibility does not exist, what will happen, what will you do?

Babel is not NodeJS and they don't have the right to tell me what I can and cannot do if the language and engine I use allows it.

If NodeJS removes it, I'll figure out another way, but my transpiler should not dictate that for me.

**Comment by killswitch** [comment]
> BTW, if nodejs finally says, such compatibility does not exist, what will happen, what will you do?

If Babel decides it doesn't like callbacks and will automatically convert all callback based functions to promises, would you allow that? Despite callbacks being a feature of NodeJS, but Babel decided it didn't approve it, now what?

**Comment by lijunle** [comment]
The transformer cannot dictate you. Nodejs cannot dictate you. Actually, ES standard cannot dictate you. Because you even can leverage [macro](http://sweetjs.org/) to write your own "JavaScript" codes.

Why do we need so many spec, standard, restrictions? Why my opinion is no. The reason is **cost**:

- How much does it cost to implement your request?
- How much will it cost if the overwriting compatibility *way* sucks?

I believe the answer for the first question is trivial. There are just [few lines](https://github.com/59naga/babel-plugin-add-module-exports/blob/master/lib/index.js) in the production code. I think, 30 min is enough to implement what you are request, including updating the test cases. (BTW, I remember an old version of this plugin is doing what you are asking, suppose [v0.0.4](https://github.com/59naga/babel-plugin-add-module-exports/blob/e27cbb99629d2989a130b961e3d95c7a3d34f270/lib/index.js))

However, how much will it cost if something sucks because of the overwriting behavior? Huge. It will be full day debugging and may cause unpredictable damage. Nobody will be aware he is overwriting some important properties, until he realize something goes wrong. For the unrealized cases, will it become a bug, or be security hole? God knows. 

Back to your question, what Babel is doing must have standard - ECMA standard. If one day, ECMA says, callback is not allowed, turn all to promise. I will argue. But if it makes sense, I will follow.

The current situation is, there is a gay between CommonJS spec and ES6 standard. Both of us agree we should fill the gap. But we do not have a *right* way, till now.
