### ISSUE TITLE
Use babel/scripts/add-module-exports as reference implementation.

### ISSUE THREAD

**Issue by jdalton** [59naga/babel-plugin-add-module-exports#34]
See [babel/scripts/add-module-exports.js](https://github.com/babel/babel/blob/master/scripts/add-module-exports.js).

**Comment by 59naga** [comment]
hmm..., in this case, the plug-in will become uneditable in this repository.
and, i care the reason that has been placed in the [packages](https://github.com/babel/babel/tree/d6576490314b0369f68b43aaaf7b49d615108ff8/packages) rather than [scripts](https://github.com/babel/babel/tree/d6576490314b0369f68b43aaaf7b49d615108ff8/scripts). 😕

**Comment by jdalton** [comment]
It's likely to be moved from scripts to a core plugin or as an option on the existing commonjs plugin.
That said, it doesn't prevent you from using their implementation as a reference for this plugin for the time being.

**Comment by 59naga** [comment]
understood. adjust my code.

**Comment by 59naga** [comment]
this change was applied as [v0.2.1](https://travis-ci.org/59naga/babel-plugin-add-module-exports/jobs/129632251#L976) now. thanks @jdalton :+1:
